# Generated by Django 2.1.1 on 2018-09-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20180912_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcomment',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
